### ISSUE TITLE
Fecha en portada y fecha en resumen

### ISSUE THREAD

**Issue by gabrieldelaparra** [Ucampus/memoria-latex#16]
Hola hola!
En `memoria.tex` hay el siguiente field: `\date{}`.
Si se coloca la fecha actual (ej.: 31/03/2020) como en la pauta, en la portada sale dicha fecha, y no el año.
Si se coloca solo el año, en la hoja de resumen, no sale la fecha como se solicita en la pauta.

**Comment by tomyahu** [comment]
No logré reproducir este problema.
Al modificar lo que está dentro de `\date{}` aparece exactamente ese contenido en la portada.
Por otro lado, la hoja de resumen del template ya no lleva fecha desde Septiembre 2019.

¿Estas usando una versión actualizada del template?

**Comment by gabrieldelaparra** [comment]
Hola Tomás,
No recuerdo muy bien el tema. Entregué a finales del año pasado. Lo solucioné colocando date{2020}. No estoy seguro que version ocupé. De todas formas cierro el issue.

Saludos!
